# Generated by Django 2.0.3 on 2018-03-31 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applied_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dof_app', models.DateField(max_length=20, null=True)),
                ('status', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='doc_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('txn', models.CharField(max_length=100)),
                ('sharedTill', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('contentType', models.CharField(max_length=100)),
                ('docType', models.CharField(max_length=100)),
                ('docId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=20, null=True)),
                ('job_description', models.CharField(max_length=20, null=True)),
                ('date_of_joining', models.DateField(max_length=20, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('flag', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='saved_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_job', to='SRS.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('middle_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('experience', models.IntegerField(null=True)),
                ('current_salary', models.IntegerField(null=True)),
                ('skills', models.CharField(max_length=50, null=True)),
                ('current_company', models.CharField(max_length=20, null=True)),
                ('current_designation', models.CharField(max_length=20, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRS.user')),
            ],
        ),
        migrations.AddField(
            model_name='saved_jobs',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='SRS.user'),
        ),
        migrations.AddField(
            model_name='doc_data',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRS.user'),
        ),
        migrations.AddField(
            model_name='applied_jobs',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_job', to='SRS.jobs'),
        ),
        migrations.AddField(
            model_name='applied_jobs',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to='SRS.user'),
        ),
    ]
